import Head from "next/head";
import Link from "next/link";

import axios from "configs/axios";

function Home(props) {

  console.log(props);

  return (
    <div className="container mx-auto mt-4">
      <Head>
        <title>Les Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className="font-sans font-normal text-3xl">Saya halaman utama</p>
        <Link href="/random">
          <a>Fetch page</a>
        </Link>
      </main>
    </div>
  );
}

Home.getInitialProps = async () => {
  try {
    const data = await axios.get(`/courses`);
    return { data: data.data.data };
  } catch (error) {
    return error;
  }
};

export default Home;
