import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div className="container mx-auto mt-4">
      <Head>
        <title>Les Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className="font-sans font-normal text-3xl">Saya halaman utama</p>
        <Link href="/random">
          <a>Fetch page</a>
        </Link>
      </main>
    </div>
  );
}
